mysql:
  host: 127.0.0.1
  port: 3306
  dbname: toktik
  username: root
  password: 123456

minio:
  url:
  port: 9000
  accessKey:
  secretKey:
  bucketName: toktik
  location: us-east-1

redis:
  host: 127.0.0.1
  port: 6379
  password: 
  db: 0